FROM golang:1.11.4-alpine3.8 AS builder

RUN apk update && \
    apk add git

WORKDIR /app

RUN go get -u github.com/golang/lint/golint
RUN go get -u github.com/jstemmer/go-junit-report
RUN go get -u github.com/axw/gocov/gocov
RUN go get -u github.com/AlekSi/gocov-xml

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build -o /go/bin/executable.bin

FROM golang:1.11.4-alpine3.8
RUN apk add --no-cache tini tzdata
RUN addgroup -g 211000 -S appgroup && adduser -u 211000 -S appuser -G appgroup
COPY --from=0 /go/bin/executable.bin /app/executable.bin
RUN chmod a+x /app/executable.bin && \
    chown -R appuser:appgroup /app
USER appuser

WORKDIR /app

ENTRYPOINT ["/sbin/tini","-sg","--","/app/executable.bin"]
