FROM nginx:1.15.12-alpine    # nginx-mod-http-headers-more is supported only nginx 1.151.2 and below

RUN apk --no-cache add shadow 'nginx-mod-http-headers-more' && \
    usermod -u 211000 nginx && \
    groupmod -g 211000 nginx
RUN chown -R nginx:nginx /etc/nginx && \
    chown -R nginx:nginx /usr/lib/nginx && \
    rm -rf /etc/nginx/conf.d/*.conf

RUN apk add --no-cache tini tzdata
RUN mkdir -p /app
COPY nginx-startup.sh /app

COPY nginx-modules.conf /etc/nginx/nginx.conf

COPY index.html /var/www/html/index.html

# Change owner all files belong to the nginx user
RUN chown -R nginx:nginx /var/www/html && \
    chown -R nginx:nginx /usr/lib/nginx && \
    chmod +x /app/nginx-startup.sh

USER nginx

ENTRYPOINT ["/sbin/tini","-sg","--","/app/nginx-startup.sh"]