FROM nginx:alpine

RUN apk --no-cache add shadow && \
    usermod -u 211000 nginx && \
    groupmod -g 211000 nginx
RUN chown -R nginx:nginx /etc/nginx
RUN rm -rf /etc/nginx/conf.d/*.conf

RUN apk add --no-cache tini tzdata
RUN mkdir -p /app
COPY startup.sh /app

COPY nginx.conf /etc/nginx/nginx.conf

COPY index.html /var/www/html/index.html

# Change owner all files belong to the nginx user
RUN chown -R nginx:nginx /var/www/html
RUN chmod +x /app/startup.sh

USER nginx

ENTRYPOINT ["/sbin/tini","-sg","--","/app/startup.sh"]